mindmap
  root((PlanEats <br/> Architecture))
    Servers
      Firebase
        Authentication
        Firestore
        Storage
        Cloud <br/>Functions
      External <br/>APIs
        App create <br/>APIs?
    frontend
         Navigation
            flash <br/>Screen
             Welcome <br/>Screen
                Authentication
                    sign up 
                        social  <br/>Network
                        email <br/>password
                    sign in
                        sign in <br/>social
                        <br/>Network
                        forgot <br/>password
                        Home <br/>Screen
                            5 Days <br/>Calendar
                            Recipe <br/>List
                             Recipe <br/>Details
                             Ingredient <br/>List
                             Preparation <br/>Steps

                            Recipe <br/>Details
                            Menu <br/>Bar
                             Home <br/>Screen
                             Favorites <br/>Recipes
                             Shopping <br/>List
                             Menu 
                                Profile
                                dietary Type
                                Allergens and <br/> Preferences
                                Favorites<br/> Recipes
                                Navigation
                                unit <br/>Measurement
                                help & <br/>Support
                                Sign out
                    
 
           
      


            